services:
  db:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bosbadb
    networks:
      - bosba_prod_network
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: rails-app
    depends_on:
      - db
    env_file:
      - .env.prod
    networks:
      - bosba_prod_network
    ports:
      - "3000:3000"
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]

networks:
  bosba_prod_network:

volumes:
  prod_postgres_data:
