services:
  db:
    image: postgres:latest
    container_name: bosba-db
    restart: always
    env_file:
      - .env.dev
    networks:
      - bosba-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bosba-app
    stdin_open: true
    depends_on:
      - db
    env_file:
      - .env.dev
    networks:
      - bosba-network
    volumes:
      - .:/app  # Syncs local files with the container (for hot reloading)
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bosba-network:

volumes:
  postgres_data:
