services:
  db:
    image: postgres:latest
    container_name: postgres-container
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bosba_prod_network
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: tykea/bosba:latest 
    container_name: bosba-container
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bosba_prod_network
    volumes:
      - prod_tmp:/app/tmp
      - prod_uploads:/app/public/uploads
    ports:
      - "3000:3000"
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]

networks:
  bosba_prod_network:

volumes:
  prod_postgres_data:
  prod_tmp:
  prod_uploads:
