# syntax = docker/dockerfile:1

# Base Image
ARG RUBY_VERSION=3.2.0
FROM docker.io/library/ruby:$RUBY_VERSION-slim

# Set working directory
WORKDIR /app

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      curl \
      nodejs \
      yarn \
      libpq-dev \
      build-essential \
      git \
      && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

# Install Bundler
RUN gem install bundler -v 2.5.21
# Set environment variables
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle" \
    PATH="/usr/local/bundle/bin:$PATH"

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 5

# Copy application code
COPY . .

ENTRYPOINT ["/app/bin/docker-entrypoint"]
# Expose port for Rails server
EXPOSE 3000

# Default command
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]

