default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '0603' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  primary:
    <<: *default
    database: clinique_dev
  primary_replica:
    <<: *default
    database: clinique_dev_replica
    replica: true

test:
  primary:
    <<: *default
    database: clinique_test
  primary_replica:
    <<: *default
    database: clinique_test_replica
    replica: true

production:
  primary:
    <<: *default
    database: <%= ENV['DB_NAME'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
  primary_replica:
    <<: *default
    database: <%= ENV['DB_NAME'] %>
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    replica: true